project:
  type: website
  output-dir: docs

website:
  description: "Linus' Blog"
  site-url: "https://linuswashere.github.io/linus_blog/"
  title: "Linus' Blog"
  navbar:
    right:
      - href: "https://linuswashere.github.io/"
        text: Home Page

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css



